a=set(input("introduceti un sir de caractere definit ca sirul a:"))
b=set(input("introduceti un sir de caractere definit ca sirul b:"))
print('a)caracterele care se întâlnesc cel puţin în unul dintre şiruri:', a.union(b))
print('b)caracterele care apar în ambele şiruri:', a.intersection(b))
print('c)caracterele care apar în primul şi nu apar în şirul al doilea:', a.difference(b))